# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-04 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
