# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-18 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_prefix', models.CharField(max_length=128, unique=True)),
                ('operation', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('parent_id', models.IntegerField()),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='urloperation',
            unique_together=set([('url_prefix', 'operation')]),
        ),
    ]
