# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-18 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20180318_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorization',
            old_name='source_id',
            new_name='resource_id',
        ),
        migrations.AlterUniqueTogether(
            name='authorization',
            unique_together=set([('resource_id', 'type')]),
        ),
    ]
